# Generated by Django 5.1.2 on 2024-11-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='completed',
            new_name='best_seller',
        ),
        migrations.RemoveField(
            model_name='base',
            name='description',
        ),
        migrations.RemoveField(
            model_name='base',
            name='title',
        ),
        migrations.AddField(
            model_name='base',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base',
            name='asin',
            field=models.CharField(default='default_asin', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='base',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='base',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='avg_review',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='category_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='base',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='base',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='price_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='product',
            field=models.TextField(default='No Product Description'),
        ),
        migrations.AddField(
            model_name='base',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='relative_popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='base',
            name='review_avg_review_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='review_rating_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
