# Generated by Django 5.0.9 on 2024-11-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_completed_base_best_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='combined_interaction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='popularity_category_max_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='popularity_global_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='predicted_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='base',
            name='price_amount_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='price_rating_interaction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='rating_review_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='base',
            name='review_amount_interaction',
            field=models.FloatField(default=0.0),
        ),
    ]
