# Generated by Django 5.0.9 on 2024-11-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_base_combined_interaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='best_seller',
        ),
    ]
