# Generated by Django 5.0.9 on 2024-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_base_best_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='amount',
            field=models.IntegerField(db_column='Amount', default=0),
        ),
        migrations.AlterField(
            model_name='base',
            name='asin',
            field=models.CharField(db_column='Asin', default='default_asin', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='avg_price',
            field=models.DecimalField(db_column='Avg_price', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='base',
            name='avg_rating',
            field=models.FloatField(db_column='Avg_rating', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='avg_review',
            field=models.FloatField(db_column='Avg_review', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='category_name',
            field=models.CharField(db_column='Category_name', default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='base',
            name='combined_interaction',
            field=models.FloatField(db_column='Combined_Interaction', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='image',
            field=models.URLField(db_column='Image', default=''),
        ),
        migrations.AlterField(
            model_name='base',
            name='popularity_category_max_ratio',
            field=models.FloatField(db_column='Popularity_Category_Max_Ratio', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='popularity_global_ratio',
            field=models.FloatField(db_column='Popularity_Global_Ratio', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='predicted_best_seller',
            field=models.BooleanField(db_column='Predicted_Best_Seller', default=False),
        ),
        migrations.AlterField(
            model_name='base',
            name='price',
            field=models.FloatField(db_column='Price', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='price_amount_ratio',
            field=models.FloatField(db_column='Price_Amount_Ratio', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='price_rating_interaction',
            field=models.FloatField(db_column='Price_Rating_Interaction', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='price_ratio',
            field=models.FloatField(db_column='Price_Ratio', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='product',
            field=models.TextField(db_column='Product', default='No Product Description'),
        ),
        migrations.AlterField(
            model_name='base',
            name='rating',
            field=models.FloatField(db_column='Rating', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='rating_review_ratio',
            field=models.FloatField(db_column='Rating_Review_Ratio', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='relative_popularity',
            field=models.FloatField(db_column='Relative_Popularity', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='review',
            field=models.IntegerField(db_column='Review', default=0),
        ),
        migrations.AlterField(
            model_name='base',
            name='review_amount_interaction',
            field=models.FloatField(db_column='Review_Amount_Interaction', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='review_avg_review_ratio',
            field=models.FloatField(db_column='Review_Avg_Review_Ratio', default=0.0),
        ),
        migrations.AlterField(
            model_name='base',
            name='review_rating_ratio',
            field=models.FloatField(db_column='Review_Rating_Ratio', default=0.0),
        ),
    ]
