# Generated by Django 5.0.9 on 2024-11-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_base_amount_alter_base_asin_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='base',
            table='Predictions',
        ),
    ]
