# Generated by Django 5.0.9 on 2024-11-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_base_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'managed': False},
        ),
    ]
